### ISSUE TITLE
Template rollback failed - unable delete config bucket, bucket not empty

### ISSUE THREAD

**Issue by navado** [awslabs/aws-perspective#57] opened 2020-10-07 16:07 UTC
when deploying the following template:
https://aws-perspective-amplifystoragebucket-14lu9llypry0f.s3.amazonaws.com/public/cfn/import-templates/regions/e1f925c485684f555c87a2fd5b792d05ecbd2bd8.template?X-Amz-Algorithm

**Comment by svozza** [comment] 2020-10-07 16:12
Thank you for the report. This is a duplicate of #30, we're looking to have a fix in the next release.

**Comment by ConnorKirk** [comment] 2020-11-04 17:05
I am going to close this issue as a duplicate of #30 , which we will use to track the fix.

Thanks again for reporting this issue Robert.

**Closed by ConnorKirk** 2020-11-04 17:05 UTC
Labels: bug, duplicate
