### ISSUE TITLE
Lambda not working and not appearing under 'Resources' in Perspective

### ISSUE THREAD

**Issue by adambjmurdoch** [awslabs/aws-perspective#28] opened 2020-09-24 09:44 UTC
**Describe the bug**
AWS Perspective deployed ok (Cloudformation completed successfully and I can login to Perspective).
However under Resources, there is no Lambda items.
Upon viewing the logs in Cloudwatch, there are 400 and 500 errors appearing as well as Alarms in Cloudwatch.

**To Reproduce**
Deployed the Cloudformation template to my account.

**Expected behavior**
Excepted the Lambda functions to operate and appear in Perspective.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment] 2020-09-24 10:04
Is it only lambda functions missing or or are there other resource types not there?

**Comment by adambjmurdoch** [comment] 2020-09-24 10:12
Well I think there are likely other resource types missing.  The only ones listed under Resources in the Perspective app are:
APIGateway(19)
ECS(1)
RDS(1)
VPC(3) - which are VPC Endpoints.

**Comment by svozza** [comment] 2020-09-24 10:27
Ah, looks like the only stuff that's been brought in are from the `decribe*` calls, there's something going on with Config, I'll bet. Are you just trying to import the Perspective account or is it a different account?

**Comment by adambjmurdoch** [comment] 2020-09-24 10:31
Yes just the Perspective account for now.

**Comment by svozza** [comment] 2020-09-24 10:37
Cool. Can you go to the Config page in the console and follow these steps:

https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html

**Comment by adambjmurdoch** [comment] 2020-09-24 11:08
Ok, thanks @svozza , it looks like you're right.  I've done Config steps and this time Config is looking better as the Dashboard is showing heaps of resources.
I haven't redeployed the CloudFormation stack yet and went into Perspective and there are some more resources showing up but still no Lambda.  Do I need to essentially redeploy the Stack?

**Comment by svozza** [comment] 2020-09-24 11:11
Cool. That's good to hear. Let the discovery process run again (it runs every fifteen minutes, so the next run will be at 12.15) and that should take care of getting all the rest of the resources.

**Comment by svozza** [comment] 2020-09-28 21:54
Did this solve your issue in the end, @adambjmurdoch ?

**Comment by svozza** [comment] 2020-09-30 16:59
I'm going to close this for now, if the issue is not resolved, please feel free to reopen.

**Closed by svozza** 2020-09-30 16:59 UTC
Labels: bug
