### ISSUE TITLE
Internal Server Error when calling /resources endpoint

### ISSUE THREAD

**Issue by StewartW** [awslabs/aws-perspective#27] opened 2020-09-24 07:58 UTC
**Describe the bug**
When trying to load you are presented with a "We could not load resource configuration" error banner. 
When invoking the /resources endpoint via API Gateway itself, this returns the following error: 
```
Endpoint response body before transformations: {"errorMessage":"Response payload size (9873641 bytes) exceeded maximum allowed payload size (6291556 bytes).","errorType":"Function.ResponseSizeTooLarge"}
```
This means that the payload size returned by [this function](https://github.com/awslabs/aws-perspective/blob/master/source/backend/functions/api/src/index.js#L451) is larger than the default 6Mb limit. 

**To Reproduce**
I guess this will be related to the amount of accounts / regions and resources. 
We currently have 10 imports from a number of accounts / regions. 

**Expected behavior**
Not to throw an error and become unusable. 
Perhaps this should page the response back or not use lambda to read from the DB
**Screenshots**
![image](https://user-images.githubusercontent.com/7794788/94117434-19110b00-fe44-11ea-99e1-08a3b7800f9c.png)

**Browser (please complete the following information):**

- Chrome
- Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

**Comment by svozza** [comment] 2020-09-24 08:44
Hi there, thanks for raising this issue. What looks like is happening is that there are so many resources being returned by the initial query to populate the Resources sidebar that it is exceeding the lambda payload limit. Unfortunately, the only workaround I have currently is to remove one of the imported accounts to bring that number down. We are currently investigating pagination strategies to mitigate this (this is a non-trivial problem with graph databases) for the next release.

**Comment by StewartW** [comment] 2020-09-24 09:23
Hey @svozza thanks for the work around. 
I've noticed that if I just filter it out certain accounts it becomes usable again.

**Comment by svozza** [comment] 2020-09-24 09:33
Ah very good, that makes sense!

**Comment by svozza** [comment] 2020-09-24 10:40
I'm going to close this now but we'll add a note to the README about this workaround while we work on a full fix.

**Closed by svozza** 2020-09-24 10:40 UTC
Labels: bug

**Comment by zainsohail88** [comment] 2020-10-08 07:57
any update on this ? we just setup a new Environment and can't even import a single account due to this.

**Comment by svozza** [comment] 2020-10-08 10:12
Hi there, we will definitely be addressing this issue but as mentioned above the solution to pagination with a graph database is not trivial (https://medium.com/@jayanta.mondal/the-curious-case-of-pagination-for-gremlin-queries-d6fd9518620) and we want to make sure that we get it right as we will have to live with that decision for a long time. Unfortunately, I can't give a firm date as to when we'll have this fixed but it is one of our top priorities.

**Comment by zainsohail88** [comment] 2020-10-08 11:21
HI @svozza I can absolutely understand that, but the problem is we are unable to complete a new setup as import is stuck from last 8 hours with message `Discovery process is scanning resources in 2 region(s)` I am able to use filters but again there are 2 issues the second being same as #33 how would I know if data has completely imported (which I don't believe has at the moment as there's no **last scanned** time in **Account & Regions** popup for 1 account and the other 1 shows **7 hours** :-(

**Comment by ConnorKirk** [comment] 2020-11-04 17:30
#87

**Comment by jeff-s-burns** [comment] 2021-03-17 15:48
I have tried filtering (single AWS account) and actually removing accounts and workarounds do not work. I can load prior created architecture diagrams but cannot update or create new.  I am unable to load any resources. "We could not load resource configuration. Refresh page to try again. See ....for help resolving this issue".

**Comment by svozza** [comment] 2021-03-17 15:51
If you open the developer tools in the browser are there any errors in the console or in the network tab?

**Comment by jeff-s-burns** [comment] 2021-03-17 16:00
Thank you for response.
  Yes, errors included.



***@***.***D71B25.139CEBF0]

From: Stefano Vozza ***@***.***>
Reply-To: awslabs/aws-perspective ***@***.***>
Date: Wednesday, March 17, 2021 at 11:51 AM
To: awslabs/aws-perspective ***@***.***>
Cc: Jeff Burns ***@***.***>, Comment ***@***.***>
Subject: Re: [awslabs/aws-perspective] Internal Server Error when calling /resources endpoint (#27)

Attention: This message was sent from an external domain.

If you open the developer tools in the browser are there any errors in the console or in the network tab?

**Comment by jeff-s-burns** [comment] 2021-03-17 16:07
Complete Error Message for 3 messages
Access to XMLHttpRequest at 'https://fba285u4a9.execute-api.us-east-1.amazonaws.com/Prod/resources?command=linkedNodesHierarchy&id=bf9b1745e44492d07cb599ec7a34aeb0' from origin 'https://d25if6jwks3j5x.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Access to XMLHttpRequest at 'https://fba285u4a9.execute-api.us-east-1.amazonaws.com/Prod/resources?command=linkedNodesHierarchy&id=bf9b1745e44492d07cb599ec7a34aeb0' from origin 'https://d25if6jwks3j5x.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

xhr.js:172 GET https://fba285u4a9.execute-api.us-east-1.amazonaws.com/Prod/resources?command=linkedNodesHierarchy&id=bf9b1745e44492d07cb599ec7a34aeb0 net::ERR_FAILED
(anonymous) @ xhr.js:172
e.exports @ xhr.js:11
e.exports @ dispatchRequest.js:57
Promise.then (async)
u.request @ Axios.js:53
(anonymous) @ bind.js:9
e._request @ RestClient.ts:363
(anonymous) @ RestClient.ts:166
(anonymous) @ 3.cddb77df.chunk.js:2
(anonymous) @ 3.cddb77df.chunk.js:2
(anonymous) @ 3.cddb77df.chunk.js:2
d @ 3.cddb77df.chunk.js:2
e.ajax @ 3.cddb77df.chunk.js:2
e.get @ RestClient.ts:186
e.get @ RestAPI.ts:114
e.get @ API.ts:74
(anonymous) @ APIHandler.js:16
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ APIHandler.js:5
(anonymous) @ APIHandler.js:67
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ APIHandler.js:66
(anonymous) @ APIHandler.js:71
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
setTimeout (async)
(anonymous) @ APIHandler.js:70
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ APIHandler.js:66
(anonymous) @ APIHandler.js:71
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
setTimeout (async)
(anonymous) @ APIHandler.js:70
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ APIHandler.js:66
(anonymous) @ APIHandler.js:71
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
setTimeout (async)
(anonymous) @ APIHandler.js:70
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ APIHandler.js:66
(anonymous) @ GraphActions.js:25
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ GraphActions.js:12
C @ TreeMenuResourceMenu.js:180
le @ TreeView.js:375
s.forwardRef.s.createElement.value.selectNode @ TreeView.js:388
onClick @ TreeItem.js:186
s @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
m @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
ot @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
L @ react-dom.production.min.js:287
U @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Qt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ho @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Yt @ react-dom.production.min.js:68
Show 34 more frames


From: Jeff Burns ***@***.***>
Date: Wednesday, March 17, 2021 at 12:00 PM
To: awslabs/aws-perspective ***@***.***>, awslabs/aws-perspective ***@***.***>
Cc: Comment ***@***.***>
Subject: Re: [awslabs/aws-perspective] Internal Server Error when calling /resources endpoint (#27)

Thank you for response.
  Yes, errors included.



***@***.***D71B26.08A160E0]

From: Stefano Vozza ***@***.***>
Reply-To: awslabs/aws-perspective ***@***.***>
Date: Wednesday, March 17, 2021 at 11:51 AM
To: awslabs/aws-perspective ***@***.***>
Cc: Jeff Burns ***@***.***>, Comment ***@***.***>
Subject: Re: [awslabs/aws-perspective] Internal Server Error when calling /resources endpoint (#27)

Attention: This message was sent from an external domain.

If you open the developer tools in the browser are there any errors in the console or in the network tab?

**Comment by svozza** [comment] 2021-03-17 16:07
Is there meant to be an image in that reply?

**Comment by jeff-s-burns** [comment] 2021-03-17 16:09
There was. I sent separate message w/ 3 of the errors

From: Stefano Vozza ***@***.***>
Reply-To: awslabs/aws-perspective ***@***.***>
Date: Wednesday, March 17, 2021 at 12:07 PM
To: awslabs/aws-perspective ***@***.***>
Cc: Jeff Burns ***@***.***>, Comment ***@***.***>
Subject: Re: [awslabs/aws-perspective] Internal Server Error when calling /resources endpoint (#27)

Attention: This message was sent from an external domain.

Is there meant to be an image in that reply?
