### ISSUE TITLE
API Request DrawIO Export returns 400 Bad request

### ISSUE THREAD

**Issue by traublmak** [awslabs/aws-perspective#92] opened 2020-11-12 14:39 UTC
**Describe the bug**
When trying to use API for export DrawIO diagram according to [doc  ](https://github.com/awslabs/aws-perspective#drawio-export)  I get 400 Bad request error with the description:
_{"errors":[{"start":{"line":1,"column":1,"offset":0},"error":" should have required property 'command'","path":""}]}_

**To Reproduce**
1. Make request to API:
`curl --location --request POST 'https://<your-api-gateway-id>.execute-api.<deployment-region>.amazonaws.com/Prod/resources' \
--header 'Authorization: Bearer <your-token> \
--header 'Content-Type: text/plain' \
--data-raw '{"elements":{"nodes":[], "edges": []}}'`

2. Get response 400 Bad request error with the description:
_{"errors":[{"start":{"line":1,"column":1,"offset":0},"error":" should have required property 'command'","path":""}]}_

**Expected behavior**
Receive a URL that when clicked will open up DrawIO in the browser and show my graph.

**Browser (please complete the following information):**

- curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**Comment by ConnorKirk** [comment] 2020-11-12 17:31
Hi @traublmak 
Thanks for opening an issue

When you tried to export a DrawIO diagram, did you have any items visualised on the canvas, or was it blank?

**Comment by traublmak** [comment] 2020-11-12 17:35
> Hi @traublmak
> Thanks for opening an issue
> 
> When you tried to export a DrawIO diagram, did you have any items visualised on the canvas, or was it blank?

Hello. This issue about REST API. I tried to export diagram using API, not UI

**Comment by ConnorKirk** [comment] 2020-11-12 17:50
Ok, I understand. Let me investigate, I will get back to you tomorrow.

**Comment by ConnorKirk** [comment] 2020-11-12 18:15
I think the example in the README is incorrect. I am sorry for the trouble caused.

Could you try using a format similar to the one below? I have got this working successfully.
Note that the `nodes` and `edges` elements in the payload needs to be populated for components to appear in the DrawIO diagram. The example below will open an empty DrawIO diagram. 
```sh
API=""
AWS_REGION=""
AUTH=""

curl -X POST "https://${API}.execute-api.${AWS_REGION}.amazonaws.com/Prod/resources" \
    --header 'Content-Type: text/plain' \
    -H "Authorization: Bearer ${AUTH}"  \
    --data-raw '{"elements":{"nodes":[], "edges": []}}'
```

**Comment by svozza** [comment] 2020-11-12 18:22
Hi @traublmak, the issue is that you need to use a different API. If you go the `aws-perspective-<accountNo><region>-ClientAPIStack` stack in the CloudFormation console you should see in `Outputs` a parameter called `DrawioRootUrl` and that is the URL to use. We will update the docs to reflect this.

**Comment by traublmak** [comment] 2020-11-13 08:13
thank you @svozza, @ConnorKirk

**Comment by toksvaeth** [comment] 2020-11-13 08:26
Looks like you had success, @traublmak.  Good to know.

If you don't mind I'm going to re-open this so we don't forget to add the documentation fixes. :)

**Comment by ConnorKirk** [comment] 2020-11-23 14:16
I am working to improve the README section for using the DrawIO API directly. This will be in the next release.

**Closed** 2021-09-16 10:16 UTC
Labels: bug, documentation, question, v1.1.0
