### ISSUE TITLE
Draw.io Fails due to CORS Policy

### ISSUE THREAD

**Issue by nazeebkadir** [awslabs/aws-perspective#232] opened 2021-11-24 15:21 UTC
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Draw.io Fails due to CORS Policy

**To Reproduce**
There are 100 widgets in the export and it fails to export the diagram to Draw.io. 

1. Go to '...' Export 
2. Click on '....' Draw.io

**Expected behavior**
Chrome Developer Console Screenshot attached.

**Screenshots**
[ScreenShots.docx](https://github.com/awslabs/aws-perspective/files/7596792/ScreenShots.docx)

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox] : Chrome
- Version [e.g. 22] :- Version 96.0.4664.45 (Official Build) (64-bit)

**Additional context**

**Comment by thebutler12** [comment] 2021-11-26 10:04
Hi, I think the CORS error is a red herring here. Can you check the logs for the **DrawIOExportFunction** Lambda function to see if there are any errors thrown in there please?

**Comment by nazeebkadir** [comment] 2021-11-29 15:55
Error Screen attached
![DrawIOExportFunction_Error](https://user-images.githubusercontent.com/92444939/143900154-2da22c6d-b115-48a8-9e52-bf39ed633cf6.JPG)

**Comment by thebutler12** [comment] 2021-11-30 13:54
This looks to be caused by a resource missing an icon. Can you confirm if any of the resources in your diagram are missing an icon within Perspective?

**Comment by thebutler12** [comment] 2021-11-30 14:37
Thanks. The icons are missing because we don't officially support VPNConnection, VPNGateway, and Customer Gateways. We will add those icons in the next release. 

For the EC2 instance, can you let us know the instance type you have provisioned? Perspective should look that up and provide an icon for the type and if it does not find an instance type specific icon, then it defaults to a standard EC2 icon.

**Comment by nazeebkadir** [comment] 2021-12-01 15:12
Missing Icons are for t4 arm instances.

**Comment by svozza** [comment] 2022-04-28 13:02
This was fixed in v1.1.3

**Closed by svozza** 2022-04-28 13:02 UTC
Labels: bug, v1.1.3
